name: unified_storefronts
description: A lightweight online storefront solution for small/local businesses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  image_picker: ^1.0.4
  path: ^1.8.3
  uuid: ^4.0.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  speech_to_text: ^6.3.0
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.0.0
  font_awesome_flutter: ^10.5.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700